apiVersion: v1
kind: Service
metadata:
  labels:
    app: student
  name: student
spec:
  ports:
    - name: tcp-8080-8080
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: student
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: student
  name: student
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: student
    spec:
      containers:
        - env:
            - name: GET_HOSTS_FROM
              value: dns
          image: eastacr.azurecr.io/student:dev
          name: student
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: acr