# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # Custom Docker Image. Primary container image where all the steps run.
      - image: maven:3

# Specify service dependencies here if necessary
# CircleCI maintains a library of pre-built images
# documented at https://circleci.com/docs/2.0/circleci-images/

    # working_directory:
      
# These steps go into the primary image
    steps:
       - checkout
       - setup_remote_docker
       - run:
          name: Install Docker Compose
          command: |
            set -x
            curl -L https://github.com/docker/compose/releases/download/1.11.2/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
            chmod +x /usr/local/bin/docker-compose && cd /usr/local/bin && ls -alrt && docker-compose version

       - run:
          name: Run Docker compose
          command: |
            docker-compose up -d 
    
       - run:
          name: Run test
          command: mvn test
       
      #  - run:
      #     name: Sonar Check
      #     command: mvn sonar:sonar -s /home/circleci/project/settings.xml
       
       - run:
          name: Maven packaging
          command: mvn clean package 

      #  - deploy:
      #     name: Build and push Docker image
      #     command: |
      #       - docker login -e $DOCKER_USER -u $DOCKER_USER -p $DOCKER_PASSWORD $REGISTRY_HOST
      #       - docker push $REGISTRY_HOST/circleci

       - store_artifacts:
          path: /tmp

# Uploading artifacts to Artifactory
       - run:
          name: Artifacts Upload
          command: |
            wget https://dl.bintray.com/jfrog/jfrog-cli-go/1.7.1/jfrog-cli-linux-amd64/jfrog
            chmod +x jfrog
            # Configure Artifactory instance with JFrog CLI
            ./jfrog rt config --url https://tcartifactory.jfrog.io/tcartifactory/libs-snapshot-local/com/tc/tsp --user admin --apikey 0BE67Uv8sl
            # Upload Artifacts to artifactory
            ./jfrog rt u "multi*/*.jar" circleci-generic-local --build-number=$CIRCLE_BUILD_NUM --flat=false
            # Collect build environment variables and build tools information using JFrog CLI
            ./jfrog rt bce circleci-generic-artifactory $CIRCLE_BUILD_NUM
            # Publish build information to Artifactory
            ./jfrog rt bp circleci-generic-artifactory $CIRCLE_BUILD_NUM

       