# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # Custom Docker Image. Primary container image where all the steps run.
      - image: maven:alpine

# Specify service dependencies here if necessary
# CircleCI maintains a library of pre-built images
# documented at https://circleci.com/docs/2.0/circleci-images/

    # working_directory:
      
# These steps go into the primary image

    steps:
       - checkout
       
       - run:
          name: Install Docker Compose
          command: |
            set -x
            curl -L https://github.com/docker/compose/releases/download/1.11.2/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
            chmod +x /usr/local/bin/docker-compose && ls -alrt /usr/local/bin 

       - setup_remote_docker
       
       - run:
          name: Run Docker compose
          command: |
            docker-compose up -d 
    
       - run:
          name: Run test
          command: mvn test
       
      #  - run:
      #     name: Sonar Check
      #     command: mvn sonar:sonar -s /home/circleci/project/settings.xml
       
       - run:
          name: Maven packaging
          command: mvn clean package

      #  - deploy:
      #     name: Build and push Docker image
      #     command: |
      #       - docker login -e $DOCKER_USER -u $DOCKER_USER -p $DOCKER_PASSWORD $REGISTRY_HOST
      #       - docker push $REGISTRY_HOST/circleci

       - store_artifacts:
          path: /home/circleci/project/ 

      